version: 2

models:
  - name: stg_addresses
    description: Demographics about each customer
    columns:
      - name: address_id    # UUID for each unique address on platform
        tests:
          - unique
      - name: address         # The first few lines of the address
      - name: zipcode         # The zipcode of the address
      - name: state           # state this delivery address is based in
      - name: country         # country this delivery address is based in
  - name: stg_events
    description: Website events
    columns:
      - name: event_id        # UUID of each unique event on the platform
        tests:
          - unique
      - name: session_id      # UUID of each browsing session on the platform which can contain many events
      - name: user_id         # UUID of the user that this event is associated with, REFERENCES users(user_id)      
      - name: page_url        # URL that the event happened on
      - name: created_at      # Timestamp of the event
      - name: event_type      # Type of event
      - name: order_id,       # If the event is specific to an order (mostly used for checkout), REFERENCES orders(order_id)
      - name: product_id      # If the event is specific to a product, REFERENCES products(product_id)
  - name: stg_order_items
    description: Detailed order information at product level
    columns:
      - name: order_id        # OrderId of this order, REFERENCES orders(order_id)
      - name: product_id      # ProductId of a single item in this order, REFERENCES products(product_id)
      - name: quantity        # Number of units of the product in this order
  - name: stg_orders
    description: Aggregate order information at order level
    columns:
      - name: order_id                # UUID for each unique order on platform
        tests:
          - unique
      - name: promo_id                # PromoId if any was used in the order
      - name: user_id                 # UserId of the user that placed this order
      - name: address_id              # Delivery address for this order             
      - name: created_at              # Timestamp when the order was created
      - name: order_cost              # Dollar about of the items in the order
      - name: shipping_cost           # Cost of shipping for the order
      - name: order_total             # Total cost of the order including shipping
      - name: tracking_id             # Tracking number for the order/package
      - name: shipping_service        # Company that was used for shipping
      - name: estimated_delivery_at   # Estimated date of delivery
      - name: delivered_at            # Actual timestamp of delivery
      - name: Status                  # Status of the order
  - name: stg_products
    description: Product catalog
    columns:
      - name: product_id      # UUID for each unique product on platform
        tests:
          - unique
      - name: name            # Name of the product
      - name: price           # Price of the product
      - name: inventory       # Amount of the inventory we have for this product
        tests:
          - positive_values
  - name: stg_promos
    description: Marketing campaign promotions
    columns:
      - name: promo_id        # Each unique promocode on platform
        tests:
          - unique
      - name: name_promo
      - name: status_promo
      - name: total_discount_usd
        tests:
          - positive_values
      - name: status          # Is the promo code active or disabled
  - name: stg_users
    description: Demographics about each user
    columns:
      - name: user_id         # UUID for each unique user on platform
        tests:
          - unique
      - name: first_name      # first name of the user
      - name: last_name       # last name of the user
      - name: email           # email address of the user
      - name: full_name       # concat first last name
      - name: user_email_domain # split part to get email domain from email
      - name: phone_number    # phone number of the user
      - name: created_at_utc      # timestamp the user was created
      - name: updated_at_utc      # timestamp the user was last updated
      - name: address_id      # default delivery address for the user