version: 2

models:
  - name: int_event_type_lta
    description: >
      Intermediate model to have events aggregate by user and sessions.
    columns:
      - name: session_id
        description: >
          Unique identifier for event
        tests:
          - not_null
      - name: created_at_utc
        description: >
          Session start time
        tests:
          - not_null
      - name: user_id
        description: >
          Unique user 
        tests:
          - not_null
      - name: page_view
        description: >
          Product or category view event
        tests:
          - not_null
          - positive_values
      - name: add_to_cart
        description: >
          .
        tests:
          - not_null
          - positive_values
      - name: checkout
        description: >
          .
        tests:
          - not_null
          - positive_values
      - name: package_shipped
        description: >
          exclude non shipped orders.
        tests:
          - not_null
          - positive_values 